# self.deleteRemoteSnapshots,
# self.deleteAllProtectionGroups,
# # self.deleteDbsResources,
# # self.deleteDbcResources,
# # self.deleteMapreduceResources,
# # self.deleateK8sClusters,
# self.deleteLBaaSResources,
# # self.deleteNfsResources,
# # self.deleteCrsResources,
# # self.deleteManagedServicesResources,
# # self.deleteEngineResources,
# self.deleteAutoscalingGroups,
# self.deleteLaunchConfigurations,
# self.deleteVmsInCluster,
# self.deleteQuotasLimits,
# self.deleteImages,
# self.deleteFloatingIps,
# self.deleteCertificates,
# self.deletePublicCertificates,
# self.deleteDirectNetworks,
# self.deleteVpcResources,
# self.deleteAllDanglingPorts,
# self.deleteAllRouters,
# self.deleteAllNetworks,
# self.deleteVips,
# self.deleteAllSecurityGroups,
# self.delete_all_vm_snapshots,
# self.deleteStorageResources,
